---
sidebar: sidebar 
permalink: codebox-automation.html 
keywords: codebox, automation 
summary: 'Codebox ist ein Co-Pilot von Infrastructure-as-Code (IAC), der Entwicklern und DevOps dabei hilft, den Code zu generieren, der für die Ausführung aller von der Workload-Fabrik unterstützten Vorgänge erforderlich ist.' 
---
= Erfahren Sie mehr über die Codebox-Automatisierung
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Codebox ist ein Co-Pilot von Infrastructure-as-Code (IAC), der Entwicklern und DevOps dabei hilft, den Code zu generieren, der für die Ausführung aller von der Workload-Fabrik unterstützten Vorgänge erforderlich ist. Codebox ist auf die Betriebsmodi der Workload-Factory (_Basic_, _Read-Only_ und _Read/Write_) abgestimmt und legt einen klaren Pfad für die Ausführungsbereitschaft fest und bietet einen Automatisierungskatalog für die schnelle zukünftige Wiederverwendung.



== Codebox-Funktionen

Codebox bietet zwei wichtige IAC-Funktionen:

* _Codebox Viewer_ zeigt die IAC an, die durch einen bestimmten Job-Flow-Vorgang erzeugt wird, indem Einträge und Auswahlen aus dem grafischen Assistenten oder aus der Konversations-Chat-Schnittstelle aufeinander abgestimmt werden. Codebox Viewer unterstützt zwar die Farbcodierung für eine einfache Navigation und Analyse, erlaubt aber keine Bearbeitung – nur das Kopieren oder Speichern von Code in den Automation Catalog.
* _Codebox Automation Catalog_ zeigt alle gespeicherten IAC-Jobs an, so dass Sie sie einfach für die zukünftige Verwendung referenzieren können. Die Aufträge im Automatisierungskatalog werden als Vorlagen gespeichert und im Kontext der Ressourcen angezeigt, die für sie gelten.


Außerdem zeigt Codebox beim Einrichten der werkseitigen Anmeldeinformationen für Workloads dynamisch die AWS-Berechtigungen an, die zum Erstellen von IAM-Richtlinien erforderlich sind. Die Berechtigungen werden für jede Workload-Factory-Funktion bereitgestellt, die Sie verwenden möchten (Datenbanken, KI, FSx für ONTAP usw.) und sie werden angepasst, je nachdem, ob die Benutzer der Richtlinie schreibgeschützte Berechtigungen oder vollständige Lese-/Schreibberechtigungen erhalten. Sie kopieren einfach die Berechtigungen aus der Codebox und fügen sie dann in die AWS Management Console ein, damit die Workload Factory die richtigen Berechtigungen für das Management Ihrer Workloads hat.



== Unterstützte Codeformate

Die unterstützten Codeformate umfassen:

* REST-APIs für die Workload-Fabrik
* AWS CLI
* AWS CloudFormation


link:use-codebox.html["Lernen Sie die Verwendung von Codebox kennen"].
