---
sidebar: sidebar 
permalink: codebox-automation.html 
keywords: codebox, automation 
summary: 'Codebox ist ein Co-Pilot für Infrastructure as Code (IaC), der Entwicklern und DevOps dabei hilft, den Code zu generieren, der zum Ausführen aller von NetApp Workload Factory unterstützten Vorgänge erforderlich ist.' 
---
= Erfahren Sie mehr über die Codebox-Automatisierung
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Codebox ist ein Infrastructure as Code (IaC) Co-Pilot, der Entwicklern und DevOps dabei hilft, den Code zu generieren, der zur Ausführung jeder von NetApp Workload Factory unterstützten Operation benötigt wird.  Codebox ist auf die Berechtigungsrichtlinien der Workload Factory abgestimmt und schafft einen klaren Weg zur Ausführungsbereitschaft. Zudem bietet es einen Automatisierungskatalog zur schnellen zukünftigen Wiederverwendung.



== Codebox-Funktionen

Codebox bietet zwei wichtige IAC-Funktionen:

* _Codebox Viewer_ zeigt die IAC an, die durch einen bestimmten Job-Flow-Vorgang erzeugt wird, indem Einträge und Auswahlen aus dem grafischen Assistenten oder aus der Konversations-Chat-Schnittstelle aufeinander abgestimmt werden. Codebox Viewer unterstützt zwar die Farbcodierung für eine einfache Navigation und Analyse, erlaubt aber keine Bearbeitung – nur das Kopieren oder Speichern von Code in den Automation Catalog.
* _Codebox Automation Catalog_ zeigt alle gespeicherten IAC-Jobs an, so dass Sie sie einfach für die zukünftige Verwendung referenzieren können. Die Aufträge im Automatisierungskatalog werden als Vorlagen gespeichert und im Kontext der Ressourcen angezeigt, die für sie gelten.


Darüber hinaus zeigt Codebox beim Einrichten der Workload Factory-Anmeldeinformationen dynamisch die AWS-Berechtigungen an, die zum Erstellen von IAM-Richtlinien erforderlich sind.  Die Berechtigungen werden für jede Workload Factory-Funktion bereitgestellt, die Sie nutzen möchten (Datenbanken, KI, FSx für ONTAP usw.), und sie sind anpassbar.  Sie kopieren einfach die Berechtigungen aus Codebox und fügen sie dann in die AWS Management Console ein, damit Workload Factory über die richtigen Berechtigungen zum Verwalten Ihrer Workloads verfügt.



== Unterstützte Codeformate

Die unterstützten Codeformate umfassen:

* Workload Factory-REST-APIs
* AWS CLI
* AWS CloudFormation
* Terraform




== Ähnliche Informationen

link:use-codebox.html["Lernen Sie die Verwendung von Codebox kennen"].

link:https://console.workloads.netapp.com/api-doc["Workload Factory REST-API-Dokumentation"^] .
