---
sidebar: sidebar 
permalink: codebox-automation.html 
keywords: codebox, automation 
summary: 'Codebox ist ein Co-Pilot für Infrastructure as Code (IaC), der Entwicklern und DevOps dabei hilft, den Code zu generieren, der zum Ausführen aller von NetApp Workload Factory unterstützten Vorgänge erforderlich ist.' 
---
= Erfahren Sie mehr über die Codebox-Automatisierung
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Codebox ist ein Co-Pilot für Infrastructure as Code (IaC), der Entwicklern und DevOps dabei hilft, den Code zu generieren, der zum Ausführen aller von NetApp Workload Factory unterstützten Vorgänge erforderlich ist.  Codebox ist auf die Betriebsmodi der Workload Factory (_basic_, _read-only_ und _read/write_) abgestimmt und legt einen klaren Pfad für die Ausführungsbereitschaft fest und bietet einen Automatisierungskatalog für die schnelle zukünftige Wiederverwendung.



== Codebox-Funktionen

Codebox bietet zwei wichtige IAC-Funktionen:

* _Codebox Viewer_ zeigt die IAC an, die durch einen bestimmten Job-Flow-Vorgang erzeugt wird, indem Einträge und Auswahlen aus dem grafischen Assistenten oder aus der Konversations-Chat-Schnittstelle aufeinander abgestimmt werden. Codebox Viewer unterstützt zwar die Farbcodierung für eine einfache Navigation und Analyse, erlaubt aber keine Bearbeitung – nur das Kopieren oder Speichern von Code in den Automation Catalog.
* _Codebox Automation Catalog_ zeigt alle gespeicherten IAC-Jobs an, so dass Sie sie einfach für die zukünftige Verwendung referenzieren können. Die Aufträge im Automatisierungskatalog werden als Vorlagen gespeichert und im Kontext der Ressourcen angezeigt, die für sie gelten.


Darüber hinaus zeigt Codebox beim Einrichten der Workload Factory-Anmeldeinformationen dynamisch die AWS-Berechtigungen an, die zum Erstellen von IAM-Richtlinien erforderlich sind.  Die Berechtigungen werden für jede Workload Factory-Funktion bereitgestellt, die Sie verwenden möchten (Datenbanken, KI, FSx für ONTAP usw.) und sie werden basierend darauf angepasst, ob die Benutzer der Richtlinie _Nur-Lese-Berechtigungen_ oder vollständige _Lese-/Schreib-Berechtigungen_ erhalten.  Sie kopieren einfach die Berechtigungen aus Codebox und fügen sie dann in die AWS-Managementkonsole ein, damit Workload Factory über die richtigen Berechtigungen zum Verwalten Ihrer Workloads verfügt.



== Unterstützte Codeformate

Die unterstützten Codeformate umfassen:

* Workload Factory-REST-APIs
* AWS CLI
* AWS CloudFormation
* Terraform




== Ähnliche Informationen

link:use-codebox.html["Lernen Sie die Verwendung von Codebox kennen"].

link:https://console.workloads.netapp.com/api-doc["Workload Factory REST-API-Dokumentation"^] .
