---
sidebar: sidebar 
permalink: configure-notifications.html 
keywords: amazon, sns, notification, topic, notifications, notifications service, alerts, email, email notifications, console notifications, filter, filtering 
summary: Sie können NetApp Workload Factory so konfigurieren, dass beim Eintreten bestimmter Ereignistypen Benachrichtigungen an eine Person oder eine andere Anwendung gesendet werden. 
---
= Konfigurieren von NetApp Workload Factory-Benachrichtigungen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Sie können den NetApp Workload Factory-Benachrichtigungsdienst so konfigurieren, dass Benachrichtigungen als Warnmeldungen in der NetApp Console, an mit dem Konto verknüpfte E-Mail-Adressen oder an ein Amazon SNS-Thema gesendet werden. Benachrichtigungen, die als Warnmeldungen gesendet werden, erscheinen in der NetApp Console, wenn Sie einen Console-Agent oder -Link bereitgestellt haben. Wenn Workload Factory Benachrichtigungen an ein Amazon SNS-Thema veröffentlicht, erhalten Abonnenten dieses Themas (wie Personen oder andere Anwendungen) die Benachrichtigungen an den für das Thema konfigurierten Endpunkten (wie E-Mail oder SMS).



== Benachrichtigungstypen und Nachrichten

Workload Factory sendet Benachrichtigungen für die folgenden Ereignisse:

[cols="6*"]
|===
| Ereignis | Beschreibung | Benachrichtigungstyp | Schweregrad | Workload | Ressourcentyp 


| Einige Datenbankinstanzen in Ihrem Konto sind nicht gut strukturiert | Alle Microsoft SQL Server-Instanzen in Ihrem Konto wurden auf gut strukturierte Probleme analysiert.  Die Beschreibung dieses Ereignisses gibt die Anzahl der gut konzipierten und nicht optimierten Instanzen an.  Überprüfen Sie die Ergebnisse und Empfehlungen zum gut strukturierten Status im Datenbankinventar der Workload Factory-Konsole. | Gut gestaltet | Empfehlung | Datenbanken | Microsoft SQL Server-Instanz 


| Die Bereitstellung des Microsoft SQL Server/PostgreSQL-Servers war erfolgreich | Die Bereitstellung des Microsoft SQL Server- oder PostgreSQL-Hosts war erfolgreich. Weitere Informationen finden Sie in der Jobüberwachung. | Einsatz | Erfolg | Datenbanken | FSx für ONTAP, DB-Host 


| Die Bereitstellung des Microsoft SQL Server/PostgreSQL-Servers ist fehlgeschlagen | Die Bereitstellung des Microsoft SQL Server- oder PostgreSQL-Hosts ist fehlgeschlagen. Weitere Informationen finden Sie in der Jobüberwachung. | Einsatz | Fehler | Datenbanken | FSx für ONTAP, DB-Host 


| Fehler beim Erstellen der Replikationsbeziehung | Die Erstellung einer SnapMirror Replikationsbeziehung ist fehlgeschlagen.  Weitere Informationen finden Sie unter Tracker. | Replikation | Kritisch | Allgemeine Lagerung | FSx für ONTAP 


| FSx für ONTAP -Erstellungsfehler | Ein FSx for ONTAP Dateisystemerstellungsprozess ist fehlgeschlagen.  Weitere Informationen finden Sie unter Tracker. | FSx für ONTAP -Dateisystemaktion | Kritisch | Allgemeine Lagerung | FSx für ONTAP 


| Automatische SSD-Kapazität oder Inodes steigern den Erfolg | Während eines kürzlich durchgeführten automatischen Kapazitätsverwaltungsupdates hat das FSx für ONTAP Dateisystem entweder die SSD-Kapazität oder die Volume-Inodes erfolgreich erhöht. Weitere Informationen finden Sie unter Tracker. | Kapazitätsmanagement | Erfolg | Allgemeine Lagerung | FSx für ONTAP Datei 


| Automatische SSD-Kapazität oder Inodes erhöhen den Ausfall | Bei einem kürzlich durchgeführten automatischen Kapazitätsverwaltungsupdate konnte das FSx für ONTAP Dateisystem die SSD-Kapazität oder die Volume-Inodes nicht erhöhen. Weitere Informationen finden Sie unter Tracker. | Kapazitätsmanagement | Kritisch | Allgemeine Lagerung | FSx für ONTAP -Dateisysteme 


| FSx für ONTAP -Problem erkannt | Alle FSx for ONTAP Dateisysteme wurden auf Probleme mit der guten Architektur analysiert.  Der Scan hat ein oder mehrere Probleme erkannt.  Weitere Informationen finden Sie in der gut strukturierten Analyse des Storage-Dashboards in der Workload Factory-Konsole. | Gut strukturierte Analyse | Empfehlung | Allgemeine Lagerung | FSx für ONTAP -Dateisysteme 


| Automatisches Kapazitätsmanagement-Ereignis für FSx für ONTAP | Die SSD-Leistungsstufe für das FSx for ONTAP Dateisystem hat den Warnschwellenwert für Kapazität/Prozentsatz erreicht. | Kapazitätsmanagement | Warnung | Allgemeine Lagerung | FSx für ONTAP -Dateisysteme 


| Automatisches Inode-Management-Ereignis für FSx für ONTAP | Die Anzahl der Inodes für das FSx for ONTAP -Volume hat den Warnschwellenwert (Anzahl/Prozentsatz) erreicht. | Kapazitätsmanagement | Warnung | Allgemeine Lagerung | FSx für ONTAP -Dateisysteme 


| Verdächtige Datenträgeraktivität im FSx für ONTAP-Dateisystem festgestellt | NetApp Autonomous Ransomware Protection mit KI (ARP/AI) hat verdächtige Volumenaktivitäten erkannt. | Schutz vor Ransomware | Kritisch | Allgemeine Lagerung | FSx für ONTAP -Dateisysteme 


| Überschreitung des Latenzschwellenwerts festgestellt | Mindestens ein Volume im FSx for ONTAP Cluster hat den Latenzschwellenwert überschritten. | Leistungsüberwachung | Warnung | EDA | FSx für ONTAP -Dateisysteme 
|===


== Konfigurieren von Workload Factory-Benachrichtigungen

Sie können Workload Factory-Benachrichtigungen mithilfe der NetApp Console oder der Workload Factory-Konsole konfigurieren.

Folgende Optionen stehen zum Empfangen von Benachrichtigungen zur Verfügung:



=== NetApp Konsole

* *Benachrichtigungen*: Konfigurieren Sie Workload Factory so, dass Benachrichtigungen gesendet werden, die unter dem Glockensymbol in NetApp Console angezeigt werden.
* *E-Mail*: Aktivieren Sie E-Mail-Benachrichtigungen in der NetApp Console, um Benachrichtigungen an alle mit dem Konto verknüpften E-Mail-Adressen zu erhalten, ohne dass eine Amazon SNS-Konfiguration erforderlich ist.
* *Amazon SNS*: Konfigurieren Sie Workload Factory so, dass Benachrichtigungen an ein Amazon SNS-Topic gesendet werden.




=== Workload Factory-Konsole

* *E-Mail*: Aktivieren Sie E-Mail-Benachrichtigungen in der Workload Factory Console, um Benachrichtigungen an alle mit dem Konto verknüpften E-Mail-Adressen zu erhalten, ohne dass eine Amazon SNS-Konfiguration erforderlich ist.
* *Amazon SNS*: Konfigurieren Sie Workload Factory so, dass Benachrichtigungen mithilfe der Workload Factory Console an ein Amazon SNS-Thema gesendet werden.



IMPORTANT: Wenn Sie Benachrichtigungen in der NetApp Console konfigurieren, übernimmt diese die Zustellung der Benachrichtigungen und die Benachrichtigungsoptionen der Workload Factory Console werden deaktiviert und im Nur-Lese-Modus angezeigt. Ein Tooltip weist darauf hin, dass Benachrichtigungen von der NetApp Console verwaltet werden. Sie können Benachrichtigungen dann nur noch über die NetApp Console verwalten.

.Bevor Sie beginnen
Die folgenden Voraussetzungen gelten nur bei der Konfiguration von Amazon SNS-Benachrichtigungen:

* Sie müssen Amazon SNS konfigurieren und Amazon SNS-Themen entweder über die Amazon SNS-Konsole oder die AWS CLI erstellen.
* Beachten Sie, dass Workload Factory den Thementyp *Standard* unterstützt.  Bei dieser Art von Thema ist nicht gewährleistet, dass die Benachrichtigungen in der Reihenfolge ihres Eingangs an die Abonnenten gesendet werden. Berücksichtigen Sie dies daher, wenn Sie kritische oder dringende Benachrichtigungen haben.


[role="tabbed-block"]
====
.Konfigurieren Sie Benachrichtigungen von der NetApp -Konsole
--
.Schritte
. Melden Sie sich an beilink:https://console.netapp.com["NetApp Konsole"^] .
. Wählen Sie im NetApp -Konsolenmenü *Workloads*, *Administration* und dann *Benachrichtigungs-Setup*.
. Aktivieren Sie auf der Seite „Benachrichtigungseinstellungen“ einen oder mehrere der folgenden Benachrichtigungstypen:
+
.. *NetApp Console-Benachrichtigungen*: Wählen Sie *NetApp Console-Benachrichtigungen aktivieren*, um Workload Factory so zu konfigurieren, dass Benachrichtigungen in der NetApp Console gesendet werden.
.. *E-Mail-Benachrichtigungen*: Wählen Sie *E-Mail-Benachrichtigungen aktivieren*, um Workload Factory so zu konfigurieren, dass Benachrichtigungen an alle mit dem Konto verknüpften E-Mail-Adressen gesendet werden.
.. *Amazon SNS-Benachrichtigungen*: Wählen Sie *SNS-Benachrichtigungen aktivieren* und folgen Sie dann den Anweisungen, um Amazon SNS aus der Amazon SNS-Konsole zu konfigurieren.
+
Nachdem Sie das Thema erstellt haben, kopieren Sie die Themen-ARN und geben Sie sie in das Feld *SNS-Thema-ARN* auf der Seite *Benachrichtigungseinrichtung* ein.



. Nachdem Sie die Konfiguration durch Senden einer Testbenachrichtigung überprüft haben, wählen Sie *Übernehmen*.


--
.Konfigurieren von Benachrichtigungen über die Workload Factory-Konsole
--
.Schritte
. Melden Sie sich an beilink:https://console.workloads.netapp.com["Workload Factory-Konsole"^] .
. Wählen Sie im Konsolenmenü von Workload Factory *Workloads*, *Administration* und dann *Benachrichtigungs-Setup* aus.
. Aktivieren Sie einen oder mehrere der folgenden Benachrichtigungstypen:
+
** *E-Mail-Benachrichtigungen*: Wählen Sie *E-Mail-Benachrichtigungen aktivieren*. Alle mit dem Konto verknüpften E-Mail-Adressen werden im Nur-Lese-Modus angezeigt.
** *Amazon SNS-Benachrichtigungen*: Wählen Sie *SNS-Benachrichtigungen aktivieren* und folgen Sie dann den Anweisungen, um Amazon SNS aus der Amazon SNS-Konsole zu konfigurieren.
+
Nachdem Sie die Konfiguration durch Senden einer Testbenachrichtigung überprüft haben, wählen Sie *Übernehmen*.





--
====


== Abonnieren Sie das Amazon SNS-Thema

Nachdem Sie Workload Factory so konfiguriert haben, dass Benachrichtigungen an ein Thema gesendet werden, folgen Sie den https://docs.aws.amazon.com/sns/latest/dg/sns-create-subscribe-endpoint-to-topic.html["Anweisungen"] in der Amazon SNS-Dokumentation, um das Thema zu abonnieren, damit Sie Benachrichtigungen von Workload Factory erhalten können.



== Benachrichtigungen filtern

Sie können unnötigen Benachrichtigungsverkehr reduzieren und bestimmte Benachrichtigungstypen gezielt an bestimmte Nutzer senden, indem Sie Filter auf die Benachrichtigungen anwenden. Sie können dies mithilfe einer Amazon SNS-Richtlinie für SNS-Benachrichtigungen und mit den Benachrichtigungseinstellungen in der NetApp Console tun.



=== Filtern von Amazon SNS-Benachrichtigungen

Wenn Sie ein Amazon SNS-Thema abonnieren, erhalten Sie standardmäßig alle zu diesem Thema veröffentlichten Benachrichtigungen.  Wenn Sie nur bestimmte Benachrichtigungen zum Thema erhalten möchten, können Sie mithilfe einer Filterrichtlinie steuern, welche Benachrichtigungen Sie erhalten.  Filterrichtlinien bewirken, dass Amazon SNS dem Abonnenten nur die Benachrichtigungen übermittelt, die der Filterrichtlinie entsprechen.

Sie können Amazon SNS-Benachrichtigungen nach den folgenden Kriterien filtern:

[cols="3*"]
|===
| Beschreibung | Feldname der Filterrichtlinie | Mögliche Werte 


| Ressourcentyp | `resourceType`  a| 
* `DB`
* `Microsoft SQL Server host`
* `PostgreSQL Server host`




| Workload | `workload` | `WLMDB` 


| Priorität | `priority`  a| 
* `Success`
* `Info`
* `Recommendation`
* `Warning`
* `Error`
* `Critical`




| Benachrichtigungstyp | `notificationType`  a| 
* `Deployment`
* `Well-architected`


|===
.Schritte
. Bearbeiten Sie in der Amazon SNS-Konsole die Abonnementdetails für das SNS-Thema.
. Wählen Sie im Bereich *Abonnementfilterrichtlinie* die Option zum Filtern nach *Nachrichtenattributen* aus.
. Aktivieren Sie die Option *Abonnementfilterrichtlinie*.
. Geben Sie eine JSON-Filterrichtlinie in das Feld *JSON-Editor* ein.
+
Beispielsweise akzeptiert die folgende JSON-Filterrichtlinie Benachrichtigungen von der Microsoft SQL Server-Ressource, die sich auf die WLMDB-Arbeitslast beziehen, die Priorität „Erfolgreich“ oder „Fehler“ haben und Details zum Status „Gut konzipiert“ bereitstellen:

+
[source, json]
----
{
  "accountId": [
    "account-a"
  ],
  "resourceType": [
    "Microsoft SQL Server host"
  ],
  "workload": [
    "WLMDB"
  ],
  "priority": [
    "Success",
    "Error"
  ],
  "notificationType": [
    "Well-architected"
  ]
}
----
. Wählen Sie *Änderungen speichern*.


Weitere Beispiele für Filterrichtlinien finden Sie unter https://docs.aws.amazon.com/sns/latest/dg/example-filter-policies.html["Beispielfilterrichtlinien für Amazon SNS"^] .

Weitere Informationen zum Erstellen von Filterrichtlinien finden Sie im https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html["Amazon SNS-Dokumentation"^] .



=== Benachrichtigungen in der NetApp Console filtern

Sie können die Benachrichtigungseinstellungen der NetApp Console verwenden, um die Benachrichtigungen, die Sie in der Console erhalten, nach Schweregrad zu filtern, wie zum Beispiel Kritisch, Info oder Warnung.

Weitere Informationen zum Filtern von Benachrichtigungen in der Konsole finden Sie im https://docs.netapp.com/us-en/console-setup-admin/task-monitor-cm-operations.html#filter-notifications["Dokumentation zur NetApp -Konsole"^] .
