---
sidebar: sidebar 
permalink: configure-notifications.html 
keywords: amazon, sns, notification, topic, notifications, notifications service, alerts 
summary: Sie können NetApp Workload Factory so konfigurieren, dass beim Eintreten bestimmter Ereignistypen Benachrichtigungen an eine Person oder eine andere Anwendung gesendet werden. 
---
= Konfigurieren von NetApp Workload Factory-Benachrichtigungen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Sie können den Benachrichtigungsdienst von NetApp Workload Factory so konfigurieren, dass Benachrichtigungen als Warnungen in der NetApp Konsole oder an ein Amazon SNS-Thema gesendet werden.  Als Warnungen gesendete Benachrichtigungen werden in der NetApp Konsole angezeigt, wenn Sie einen Konsolenagenten oder -link bereitgestellt haben.  Wenn Workload Factory Benachrichtigungen zu einem Amazon SNS-Thema veröffentlicht, erhalten Abonnenten des Themas (z. B. Personen oder andere Anwendungen) die Benachrichtigungen an den für das Thema konfigurierten Endpunkten (z. B. E-Mail- oder SMS-Nachrichten).



== Benachrichtigungstypen und Nachrichten

Workload Factory sendet Benachrichtigungen für die folgenden Ereignisse:

[cols="6*"]
|===
| Ereignis | Beschreibung | Benachrichtigungstyp | Schweregrad | Workload | Ressourcentyp 


| Einige Datenbankinstanzen in Ihrem Konto sind nicht gut strukturiert | Alle Microsoft SQL Server-Instanzen in Ihrem Konto wurden auf gut strukturierte Probleme analysiert.  Die Beschreibung dieses Ereignisses gibt die Anzahl der gut konzipierten und nicht optimierten Instanzen an.  Überprüfen Sie die Ergebnisse und Empfehlungen zum gut strukturierten Status im Datenbankinventar der Workload Factory-Konsole. | Gut gestaltet | Empfehlung | Datenbanken | Microsoft SQL Server-Instanz 


| Die Bereitstellung des Microsoft SQL Server/PostgreSQL-Servers war erfolgreich | Die Bereitstellung des Microsoft SQL Server- oder PostgreSQL-Hosts war erfolgreich. Weitere Informationen finden Sie in der Jobüberwachung. | Einsatz | Erfolg | Datenbanken | FSx für ONTAP, DB-Host 


| Die Bereitstellung des Microsoft SQL Server/PostgreSQL-Servers ist fehlgeschlagen | Die Bereitstellung des Microsoft SQL Server- oder PostgreSQL-Hosts ist fehlgeschlagen. Weitere Informationen finden Sie in der Jobüberwachung. | Einsatz | Fehler | Datenbanken | FSx für ONTAP, DB-Host 


| Fehler beim Erstellen der Replikationsbeziehung | Die Erstellung einer SnapMirror Replikationsbeziehung ist fehlgeschlagen.  Weitere Informationen finden Sie unter Tracker. | Replikation | Kritisch | Allgemeine Lagerung | FSx für ONTAP 


| FSx für ONTAP -Erstellungsfehler | Ein FSx for ONTAP Dateisystemerstellungsprozess ist fehlgeschlagen.  Weitere Informationen finden Sie unter Tracker. | FSx für ONTAP -Dateisystemaktion | Kritisch | Allgemeine Lagerung | FSx für ONTAP 


| Automatische SSD-Kapazität oder Inodes steigern den Erfolg | Während eines kürzlich durchgeführten automatischen Kapazitätsverwaltungsupdates hat das FSx für ONTAP Dateisystem entweder die SSD-Kapazität oder die Volume-Inodes erfolgreich erhöht. Weitere Informationen finden Sie unter Tracker. | Kapazitätsmanagement | Erfolg | Allgemeine Lagerung | FSx für ONTAP Datei 


| Automatische SSD-Kapazität oder Inodes erhöhen den Ausfall | Bei einem kürzlich durchgeführten automatischen Kapazitätsverwaltungsupdate konnte das FSx für ONTAP Dateisystem die SSD-Kapazität oder die Volume-Inodes nicht erhöhen. Weitere Informationen finden Sie unter Tracker. | Kapazitätsmanagement | Kritisch | Allgemeine Lagerung | FSx für ONTAP -Dateisysteme 


| FSx für ONTAP -Problem erkannt | Alle FSx for ONTAP Dateisysteme wurden auf Probleme mit der guten Architektur analysiert.  Der Scan hat ein oder mehrere Probleme erkannt.  Weitere Informationen finden Sie in der gut strukturierten Analyse des Storage-Dashboards in der Workload Factory-Konsole. | Gut strukturierte Analyse | Empfehlung | Allgemeine Lagerung | FSx für ONTAP -Dateisysteme 
|===


== Konfigurieren von Workload Factory-Benachrichtigungen

Konfigurieren Sie Workload Factory-Benachrichtigungen mithilfe der NetApp -Konsole oder der Workload Factory-Konsole.  Wenn Sie die NetApp Konsole verwenden, können Sie Workload Factory so konfigurieren, dass Benachrichtigungen als Warnungen in der NetApp Konsole oder an ein Amazon SNS-Thema gesendet werden.  Sie können Benachrichtigungen in den *Benachrichtigungseinstellungen* in der NetApp Konsole konfigurieren.

.Bevor Sie beginnen
* Sie müssen Amazon SNS konfigurieren und Amazon SNS-Themen entweder über die Amazon SNS-Konsole oder die AWS CLI erstellen.
* Beachten Sie, dass Workload Factory den Thementyp *Standard* unterstützt.  Bei dieser Art von Thema ist nicht gewährleistet, dass die Benachrichtigungen in der Reihenfolge ihres Eingangs an die Abonnenten gesendet werden. Berücksichtigen Sie dies daher, wenn Sie kritische oder dringende Benachrichtigungen haben.


[role="tabbed-block"]
====
.Konfigurieren Sie Benachrichtigungen von der NetApp -Konsole
--
.Schritte
. Melden Sie sich an beilink:https://console.netapp.com["NetApp Konsole"^] .
. Wählen Sie im NetApp -Konsolenmenü *Workloads*, *Administration* und dann *Benachrichtigungs-Setup*.
. Gehen Sie auf der Einrichtungsseite für Benachrichtigungen wie folgt vor:
+
.. Optional: Wählen Sie *Benachrichtigungen der NetApp Konsole aktivieren*, um Workload Factory zum Senden von Benachrichtigungen in der NetApp Konsole zu konfigurieren.
.. Wählen Sie *SNS-Benachrichtigungen aktivieren*.
.. Befolgen Sie die Anweisungen zum Konfigurieren von Amazon SNS über die Amazon SNS-Konsole.
+
Nachdem Sie das Thema erstellt haben, kopieren Sie die Themen-ARN und geben Sie sie in das Feld *SNS-Thema-ARN* auf der Seite *Benachrichtigungseinrichtung* ein.



. Nachdem Sie die Konfiguration durch Senden einer Testbenachrichtigung überprüft haben, wählen Sie *Übernehmen*.


.Ergebnis
Workload Factory ist so konfiguriert, dass Benachrichtigungen an das von Ihnen angegebene Amazon SNS-Thema gesendet werden.

--
.Konfigurieren von Benachrichtigungen über die Workload Factory-Konsole
--
.Schritte
. Melden Sie sich an beilink:https://console.workloads.netapp.com["Workload Factory-Konsole"^] .
. Wählen Sie im Konsolenmenü von Workload Factory *Workloads*, *Administration* und dann *Benachrichtigungs-Setup* aus.
. Wählen Sie *SNS-Benachrichtigungen aktivieren*.
. Befolgen Sie die Anweisungen zum Konfigurieren von Amazon SNS über die Amazon SNS-Konsole.
. Nachdem Sie die Konfiguration durch Senden einer Testbenachrichtigung überprüft haben, wählen Sie *Übernehmen*.


.Ergebnis
Workload Factory ist so konfiguriert, dass Benachrichtigungen an das von Ihnen angegebene Amazon SNS-Thema gesendet werden.

--
====


== Abonnieren Sie das Amazon SNS-Thema

Nachdem Sie Workload Factory so konfiguriert haben, dass Benachrichtigungen an ein Thema gesendet werden, folgen Sie den https://docs.aws.amazon.com/sns/latest/dg/sns-create-subscribe-endpoint-to-topic.html["Anweisungen"] in der Amazon SNS-Dokumentation, um das Thema zu abonnieren, damit Sie Benachrichtigungen von Workload Factory erhalten können.



== Benachrichtigungen filtern

Sie können unnötigen Benachrichtigungsverkehr reduzieren und bestimmte Benachrichtigungstypen gezielt auf bestimmte Benutzer ausrichten, indem Sie Filter auf die Benachrichtigungen anwenden.  Sie können dies mithilfe einer Amazon SNS-Richtlinie für SNS-Benachrichtigungen und mithilfe der Benachrichtigungseinstellungen in der NetApp Konsole tun.



=== Filtern von Amazon SNS-Benachrichtigungen

Wenn Sie ein Amazon SNS-Thema abonnieren, erhalten Sie standardmäßig alle zu diesem Thema veröffentlichten Benachrichtigungen.  Wenn Sie nur bestimmte Benachrichtigungen zum Thema erhalten möchten, können Sie mithilfe einer Filterrichtlinie steuern, welche Benachrichtigungen Sie erhalten.  Filterrichtlinien bewirken, dass Amazon SNS dem Abonnenten nur die Benachrichtigungen übermittelt, die der Filterrichtlinie entsprechen.

Sie können Amazon SNS-Benachrichtigungen nach den folgenden Kriterien filtern:

[cols="3*"]
|===
| Beschreibung | Feldname der Filterrichtlinie | Mögliche Werte 


| Ressourcentyp | `resourceType`  a| 
* `DB`
* `Microsoft SQL Server host`
* `PostgreSQL Server host`




| Workload | `workload` | `WLMDB` 


| Priorität | `priority`  a| 
* `Success`
* `Info`
* `Recommendation`
* `Warning`
* `Error`
* `Critical`




| Benachrichtigungstyp | `notificationType`  a| 
* `Deployment`
* `Well-architected`


|===
.Schritte
. Bearbeiten Sie in der Amazon SNS-Konsole die Abonnementdetails für das SNS-Thema.
. Wählen Sie im Bereich *Abonnementfilterrichtlinie* die Option zum Filtern nach *Nachrichtenattributen* aus.
. Aktivieren Sie die Option *Abonnementfilterrichtlinie*.
. Geben Sie eine JSON-Filterrichtlinie in das Feld *JSON-Editor* ein.
+
Beispielsweise akzeptiert die folgende JSON-Filterrichtlinie Benachrichtigungen von der Microsoft SQL Server-Ressource, die sich auf die WLMDB-Arbeitslast beziehen, die Priorität „Erfolgreich“ oder „Fehler“ haben und Details zum Status „Gut konzipiert“ bereitstellen:

+
[source, json]
----
{
  "accountId": [
    "account-a"
  ],
  "resourceType": [
    "Microsoft SQL Server host"
  ],
  "workload": [
    "WLMDB"
  ],
  "priority": [
    "Success",
    "Error"
  ],
  "notificationType": [
    "Well-architected"
  ]
}
----
. Wählen Sie *Änderungen speichern*.


Weitere Beispiele für Filterrichtlinien finden Sie unter https://docs.aws.amazon.com/sns/latest/dg/example-filter-policies.html["Beispielfilterrichtlinien für Amazon SNS"^] .

Weitere Informationen zum Erstellen von Filterrichtlinien finden Sie im https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html["Amazon SNS-Dokumentation"^] .



=== Filtern von Benachrichtigungen in der NetApp Konsole

Sie können die Benachrichtigungseinstellungen der NetApp Konsole verwenden, um Benachrichtigungen, die Sie in der Konsole erhalten, nach Schweregrad zu filtern, z. B. „Kritisch“, „Info“ oder „Warnung“.

Weitere Informationen zum Filtern von Benachrichtigungen in der Konsole finden Sie im https://docs.netapp.com/us-en/console-setup-admin/task-monitor-cm-operations.html#filter-notifications["Dokumentation zur NetApp -Konsole"^] .
