---
sidebar: sidebar 
permalink: console-experiences.html 
keywords: console, consoles, access, saas, Workload Factory, NetApp Workload Factory, NetApp Console 
summary: Auf NetApp Workload Factory kann über zwei webbasierte Konsolen zugegriffen werden. 
---
= Konsolenerfahrungen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Auf NetApp Workload Factory kann über zwei webbasierte Konsolen zugegriffen werden.  Erfahren Sie, wie Sie über die Workload Factory-Konsole und die NetApp -Konsole auf Workload Factory zugreifen.

* * NetApp Konsole*: Bietet eine Hybriderfahrung, bei der Sie Ihre FSx für ONTAP -Dateisysteme und Workloads, die auf Amazon FSx for NetApp ONTAP ausgeführt werden, am selben Ort verwalten können.
* *Workload Factory-Konsole*: Bietet eine dedizierte Workload Factory-Erfahrung mit Schwerpunkt auf Workloads, die auf Amazon FSx for NetApp ONTAP ausgeführt werden.




== Zugriff auf Workload Factory in der NetApp -Konsole

Sie können über die NetApp Console auf Workload Factory zugreifen. Zusätzlich zur Nutzung von Workload Factory für AWS-Speicher- und Workload-Funktionen können Sie auch auf andere Datendienste wie NetApp Copy and Sync und mehr zugreifen.

.Schritte
. Melden Sie sich an beilink:https://console.netapp.com["NetApp Konsole"^] .
. Wählen Sie im NetApp -Konsolenmenü *Workloads* und dann *Übersicht* aus.




== Greifen Sie in der Workload Factory-Konsole auf Workload Factory zu

Sie können über die Workload Factory-Konsole auf Workload Factory zugreifen.

.Schritt
. Melden Sie sich an beilink:https://console.workloads.netapp.com["Workload Factory-Konsole"^] .

