---
sidebar: sidebar 
permalink: manage-credentials.html 
keywords: aws accounts, aws, credentials, edit credentials, manage credentials, delete credentials 
summary: Wenn Sie einen Satz Anmeldeinformationen nicht mehr benötigen, können Sie ihn aus NetApp Workload Factory löschen.  Sie können nur Anmeldeinformationen löschen, die nicht mit einem FSx for ONTAP Dateisystem verknüpft sind. 
---
= Entfernen Sie die Anmeldeinformationen aus der NetApp Workload Factory
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie einen Satz Anmeldeinformationen nicht mehr benötigen, können Sie ihn aus Workload Factory löschen.  Sie können nur Anmeldeinformationen löschen, die nicht mit einem FSx for ONTAP Dateisystem verknüpft sind.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie im Menü *Administration* und dann *Anmeldeinformationen*.
. Führen Sie auf der Seite *Anmeldeinformationen* die folgenden Schritte aus:
+
** Wählen Sie in der Workload Factory-Konsole das Aktionsmenü für einen Satz von Anmeldeinformationen und dann *Entfernen* aus. Wählen Sie zur Bestätigung *Entfernen*.
** Wählen Sie in der NetApp Konsole das Aktionsmenü für einen Satz Anmeldeinformationen und dann *Löschen* aus. Wählen Sie zur Bestätigung *Löschen*.



