---
settings:
  name: Setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Installations- und Administrationsdokumente
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
  - title: Los geht's
    entries:
    - title: Lernen Sie die Grundlagen kennen
      entries:
      - title: Übersicht über Workload Factory
        url: "/workload-factory-overview.html"
      - title: Betriebsmodi
        url: "/operational-modes.html"
    - title: Schnellstart
      url: "/quick-start.html"
    - title: Melden Sie sich bei Workload Factory an
      url: "/sign-up-saas.html"
    - title: AWS-Anmeldedaten hinzufügen
      url: "/add-credentials.html"
    - title: Was Sie als Nächstes tun können
      url: "/whats-next.html"
  - title: Verwaltung Von Workload Factory
    entries:
    - title: Melden Sie sich bei Workload Factory an
      url: "/log-in.html"
    - title: Automatisieren Sie Aufgaben mit der Codebox
      entries:
      - title: Erfahren Sie mehr über Codebox
        url: "/codebox-automation.html"
      - title: Codebox verwenden, um Code zu generieren
        url: "/use-codebox.html"
    - title: Anmeldedaten entfernen
      url: "/manage-credentials.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP Workload Factory for AWS
  repo: workload-family
