---
settings:
  name: Setup and administration
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Installations- und Administrationsdokumente
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
  - title: Los geht's
    entries:
    - title: Lernen Sie die Grundlagen kennen
      entries:
      - title: Erfahren Sie mehr 端ber NetApp Workload Factory
        url: "/workload-factory-overview.html"
      - title: Betriebsmodi
        url: "/operational-modes.html"
      - title: Konsolenerfahrungen
        url: "/console-experiences.html"
      - title: Berechtigungen
        url: "/permissions-reference.html"
    - title: Schnellstart
      url: "/quick-start.html"
    - title: Registrieren Sie sich bei Workload Factory
      url: "/sign-up-saas.html"
    - title: AWS-Anmeldedaten hinzuf端gen
      url: "/add-credentials.html"
    - title: Optimieren Sie Workloads mit Workload Factory
      url: "/whats-next.html"
  - title: Workload Factory verwalten
    entries:
    - title: Melden Sie sich bei Workload Factory an
      url: "/log-in.html"
    - title: Verwalten von Servicekonten
      url: "/manage-service-accounts.html"
    - title: Konfigurieren Sie Benachrichtigungen
      url: "/configure-notifications.html"
    - title: Automatisieren Sie Aufgaben mit der Codebox
      entries:
      - title: Erfahren Sie mehr 端ber Codebox
        url: "/codebox-automation.html"
      - title: Codebox verwenden, um Code zu generieren
        url: "/use-codebox.html"
    - title: Verwenden Sie CloudShell
      url: "/use-cloudshell.html"
    - title: Anmeldedaten entfernen
      url: "/manage-credentials.html"
  - title: Wissen und Support
    entries:
    - title: F端r den Support anmelden
      url: "/support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: NetApp Workload Factory
  repo: workload-family
