---
sidebar: sidebar 
permalink: well-architected-workloads.html 
keywords: well-architected, best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: Workload Factory scannt Workload-Konfigurationen auf Zuverlässigkeit, Sicherheit, operative Exzellenz, Kostenoptimierung und Leistungseffizienz und liefert Erkenntnisse und Empfehlungen, die Ihnen helfen, operative Exzellenz zu erreichen. 
---
= Gut strukturierte Workloads erstellen und betreiben
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory, die NetApp -Management-Suite für Amazon FSx for NetApp ONTAP, unterstützt Sie bei der Wartung und dem Betrieb zuverlässiger, sicherer, effizienter und kostengünstiger Speicher- und Datenbankkonfigurationen, die mit dem AWS Well-Architected Framework übereinstimmen. Workload Factory bietet tägliche Analysen Ihrer Speicher- und Datenbank-Workloads, Empfehlungen und automatische Korrekturen, um einen reibungslosen Workload-Betrieb zu gewährleisten. Durch die Automatisierung dieses Prozesses minimiert Workload Factory menschliche Fehler und gewährleistet Konsistenz im Workload-Management.



== So funktioniert es

Workload Factory analysiert Amazon FSx for NetApp ONTAP-Dateisysteme, Microsoft SQL Server und Oracle-Datenbankbereitstellungen täglich. Die Analyse liefert einen well-architected Status, Erkenntnisse und Empfehlungen. Sie können Konfigurationsprobleme automatisch beheben, um Best Practices zu erfüllen und effizient zu arbeiten.

Nach Abschluss der täglichen Analyse werden die Konfigurationen im Well-architected-Dashboard für die Bereitstellung als „optimiert“ oder „nicht optimiert“ angezeigt. Sie finden dort die Gesamtoptimierungspunktzahl, Konfigurationsprobleme nach Kategorie sowie eine Liste der Konfigurationsprobleme und Empfehlungen. Sie können die Empfehlungen zu Konfigurationsproblemen einsehen. Manche Probleme können von Workload Factory automatisch behoben werden, andere erfordern einen manuellen Eingriff. In diesem Fall stellt Workload Factory detaillierte Anweisungen bereit, die Ihnen bei der Umsetzung der empfohlenen Änderungen helfen.

Sie können die Analyse von Konfigurationen, die für Ihre Umgebungen nicht gelten, ausblenden. Dadurch werden unnötige Warnmeldungen und ungenaue Optimierungsergebnisse vermieden. Wenn Sie eine bestimmte Konfigurationsanalyse ausblenden, berücksichtigt Workload Factory die Konfiguration nicht in der Gesamtoptimierungsbewertung.



== Warum es wichtig ist

Workload Factory wendet Best Practices auf große Speicher- oder Datenbankumgebungen an, indem kontinuierliche Bewertungen mit Empfehlungseinblicken und Fehlerbehebungen kombiniert werden. Automatisierte Korrekturen reduzieren menschliche Fehler, gewährleisten einheitliches Management und erhalten Leistung und Zuverlässigkeit. In der Workload Factory-Konsole angewendete Korrekturen reduzieren menschliche Fehler und gewährleisten einheitliches Management. Automatisierung stellt sicher, dass Konfigurationen korrekt angewendet und gepflegt werden, wodurch Leistung und Zuverlässigkeit in Ihren Workload-Infrastrukturen erhalten bleiben.



== Legen Sie mit Workload Factory los, um Fehlkonfigurationen zu erkennen und zu korrigieren.

Um mit Workload Factory zu beginnen, registrieren Sie sich, fügen Sie Anmeldeinformationen hinzu und stellen Sie eine Verbindung her, um AWS-Ressourcen zu verwalten und Workloads mithilfe von Amazon FSx for NetApp ONTAP zu optimieren.

link:https://docs.netapp.com/us-en/workload-setup-admin/quick-start.html["Schnellstart"]



== Bewährte Verfahren und Empfehlungen für Speicherworkloads

Workload Factory analysiert Speicherkonfigurationen, um einen detaillierten Überblick über Best Practices für die ONTAP-Konfiguration und die Einhaltung des AWS Well-Architected Frameworks zu bieten. Die Analyse empfiehlt außerdem Verbesserungen und Fehlerbehebungen.

Die gut strukturierte Analyse kategorisiert Konfigurationen anhand der folgenden Säulen des Rahmenwerks: Zuverlässigkeit, Sicherheit, operative Exzellenz, Kostenoptimierung und Leistungseffizienz.



=== Zuverlässigkeit

Zuverlässigkeit gewährleistet, dass Arbeitslasten ihre beabsichtigten Funktionen auch bei Störungen korrekt und konsistent erfüllen.

* *FSx für ONTAP Backups planen*
+
FSx for ONTAP: Die Sicherung Ihrer Volumes unterstützt die Einhaltung von Datenaufbewahrungs- und Compliance-Vorgaben. Verwenden Sie FSx for ONTAP Backup, um automatisierte Backups und Aufbewahrung für Ihre Daten einzurichten.

* *Lokale Snapshots planen*
+
Planen Sie lokale Snapshots für effiziente Datensicherung und schnelle Wiederherstellung. Snapshots sind Momentaufnahmen Ihrer Volumes zu einem bestimmten Zeitpunkt.

* *Regionenübergreifende Replikation*
+
Die regionsübergreifende Replikation stellt sicher, dass Ihre Daten in eine andere AWS-Region repliziert werden und bietet so eine verbesserte Datenbeständigkeit und Verfügbarkeit. Workload Factory empfiehlt die Einrichtung der regionsübergreifenden Replikation, um bei der Notfallwiederherstellung und Compliance zu unterstützen.

* *Datenreplikation einrichten*
+
Um die Datenzuverlässigkeit zu erhöhen, können Daten auf ein FSx for ONTAP -Dateisystem in derselben Region oder in einer anderen Region repliziert werden. Richten Sie eine Datenreplikation ein, um Migration, Notfallwiederherstellung und langfristige Aufbewahrung über Dateisysteme hinweg zu unterstützen.

* *SSD-Kapazitätsschwelle erhöhen*
+
Die SSD-Speicherkapazität sollte dauerhaft nicht zu mehr als 80 % ausgelastet sein. Dies könnte sich auf Lese- und Schreibvorgänge von Daten in Ihrem Kapazitätspool-Speicherbereich auswirken und die Durchsatzkapazität Ihres Dateisystems beeinträchtigen. Wenn die Speicherkapazität erschöpft ist, kann dies dazu führen, dass Datenmengen schreibgeschützt werden und Dienste, die versuchen, neue Daten zu schreiben, fehlschlagen.

* *Zugleichung der Beschriftungen zur Sicherstellung der Datenzuverlässigkeit*
+
Um die Datenzuverlässigkeit zu gewährleisten, müssen die Snapshot-Richtlinienbezeichnungen des Quellvolumes und die Replikationsrichtlinienbezeichnungen übereinstimmen.

* *Dateikapazitätsschwelle erhöhen*
+
Der Schwellenwert für die Dateikapazität sollte erhöht werden, um ein Erreichen der Speicherkapazitätsgrenze zu vermeiden. Eine geringe Dateikapazität (Inodes) verhindert das Schreiben zusätzlicher Daten auf das Volume. Workload Factory empfiehlt, die Auslastung der verfügbaren Dateikapazität dauerhaft unter 80 % zu halten. Um neue Dateien im Volume zu erstellen, wird freier Dateispeicher benötigt.





=== Sicherheit

Im Bereich der Sicherheit liegt der Schwerpunkt auf dem Schutz von Daten, Systemen und Vermögenswerten durch Risikobewertungen und Risikominderungsstrategien.

* *ARP/AI aktivieren*
+
NetApp Autonomous Ransomware Protection mit KI (ARP/AI) hilft, Ihre Volumes vor Ransomware-Bedrohungen zu schützen. Workload Factory empfiehlt, ARP/AI für alle Volumes zu aktivieren.

* *Unbefugter Zugriff auf Datenträger*
+
Datenträger, die Anwendungsdaten über iSCSI bereitstellen, sollten keinen parallelen NAS-Zugriff zulassen. Workload Factory empfiehlt, dass auf Volumes, die über das iSCSI-Protokoll zugegriffen werden, keine weiteren Protokolle verwendet werden dürfen.





=== Operative Exzellenz

Operative Exzellenz konzentriert sich auf die Bereitstellung einer optimalen Architektur und eines optimalen Geschäftswerts.

* *Automatische Kapazitätsverwaltung aktivieren*
+
Die automatische Kapazitätsverwaltung sollte aktiviert werden, um regelmäßig sicherzustellen, dass die SSD-Ebene den Schwellenwert nicht überschreitet.

* *Auslastungsschwelle für Volumenkapazität*
+
Workload Factory empfiehlt, dass die Auslastung der Volumenkapazität dauerhaft 80 % nicht überschreiten sollte. Dies könnte Auswirkungen auf Lese- und Schreibvorgänge Ihrer Anwendung haben. Die Volumenkapazität kann manuell oder automatisch mithilfe der Funktion „Volumen automatisch vergrößern“ erhöht werden.

* *Die Volumenauslastung nähert sich der Vollauslastung*
+
Wenn ein Datenvolumen fast seine volle Kapazität erreicht, empfiehlt Workload Factory, Maßnahmen zur Erhöhung der Volumenkapazität zu ergreifen, um potenzielle Anwendungsunterbrechungen zu vermeiden.

* *Schreibmodus für Cache-Beziehungen*
+
Für eine optimale Leistung empfiehlt Workload Factory den Cache-Beziehungsschreibmodus, der am besten zu Ihrer Arbeitslast passt. Der Write-Around-Modus bietet eine bessere Leistung bei leseintensiven Arbeitslasten mit kleinen Dateien, während der Write-Back-Modus eine bessere Leistung bei schreibintensiven Arbeitslasten mit großen Dateien bietet.

* *Cache-Volume-Größe optimieren*
+
Workload Factory empfiehlt, die automatische Größenanpassung und das Scrubbing auf Cache-Volumes zu aktivieren, um eine optimale Größe beizubehalten und den Cache auf Hot Data für maximale Effizienz zu fokussieren.

* *Logische Berichterstellung für Storage-VMs*
+
Workload Factory empfiehlt, dass die Standardeinstellung für die Berichtserstellung für eine Speicher-VM auf logisch gesetzt wird, um eine bessere Sichtbarkeit der Speichernutzung auf Volume-Ebene zu bieten.





=== Kostenoptimierung

Kostenoptimierung hilft Ihnen, den größtmöglichen Nutzen für Ihr Unternehmen zu erzielen und gleichzeitig die Kosten niedrig zu halten.

* *Optimieren Sie die Gesamtbetriebskosten durch Staffelung der Kaltdaten*
+
Um die Auslastung der SSD-Speicherebene zu reduzieren, sollte Cold Data Tiering aktiviert werden. Es wird empfohlen, für jedes Volumen eine Staffelungsrichtlinie anzuwenden. FSx for ONTAP scannt die Daten kontinuierlich, um selten genutzte Daten zu erkennen und diese unterbrechungsfrei in den Speicherpool mit hoher Kapazität zu verschieben.

* *Speichereffizienz aktivieren*
+
Um die Speicherauslastung zu optimieren und die Kosten der SSD-Ebene zu senken, sollten Speichereffizienzmaßnahmen wie Komprimierung, Verdichtung und Deduplizierung aktiviert werden.

* *Unnötige Löschung von Snapshots und Backups*
+
Um Kosten zu sparen, sollten nicht mehr benötigte Snapshots und Backups gelöscht werden.

* *Verwaiste Blockgeräte*
+
Nachdem ein Blockgerät sieben Tage lang nicht verwendet wurde, empfiehlt Workload Factory, die Blockgerätedaten zu archivieren oder das ungenutzte Blockgerät zu löschen, um Kosten zu senken.





== Bewährte Verfahren und Empfehlungen für Datenbank-Workloads

Workload Factory bietet eine Reihe von Best Practices und Empfehlungen für den Betrieb gut strukturierter Datenbank-Workloads. Die gut durchdachte Analyse bewertet die Konfigurationen und Einstellungen von Microsoft SQL Server und Oracle Database in Bezug auf Speicherdimensionierung, Speicherlayout, Speicherkonfiguration, Rechenleistung, Anwendung (SQL Server) und Ausfallsicherheit.



=== Speichergrößen

* *Speicherebene*
+
Für optimale Speicherleistung erstellen Sie FSx for ONTAP-Volumes auf der primären SSD-Ebene. Die Verwendung der Kapazitätspool-Ebene kann die Leistung verlangsamen und die Latenz erhöhen.

* *Freier Speicherplatz im Dateisystem*
+
Um die Speicherleistung zu optimieren, stellen Sie die Dateisystemkapazität auf das 1,35-fache der Gesamtgröße Ihrer Volumes ein.

+
Die prozentualen Spielraumreserven des Dateisystems sind wie folgt:

+
** Unterversorgt: < 35 %
** Optimiert: 35–100 %
** Überversorgung: > 100 %


* *Speicherlaufwerkgröße*
+
Um Probleme wie Transaktions-Rollbacks, Datenbankausfälle, Datenbeschädigung und Leistungseinbußen durch ein volles Protokolllaufwerk zu vermeiden, ist eine genaue Dimensionierung und regelmäßige Überwachung des SQL Server-Protokolllaufwerks erforderlich.

+
Die prozentuale Verteilung der Log-Laufwerksgröße ist wie folgt:

+
** Unterversorgt: < 20 %
** Optimiert: 20-30 %
** Überversorgung: > 30 %


* *TempDB-Laufwerksgröße*
+
Um die Leistung zu optimieren und die Gesamtstabilität zu gewährleisten, ist eine genaue Dimensionierung und regelmäßige Überwachung der SQL Server TempDB erforderlich. Eine korrekt konfigurierte TempDB verhindert Leistungsprobleme und Instabilität. Unzureichender Speicherplatz oder hohe Konflikte können zu Verzögerungen bei Abfragen, Anwendungstimeouts und Systemabstürzen führen.

+
Die prozentualen Anteile der TempDB-Laufwerksgröße sind wie folgt:

+
** Unterversorgt: < 10 %
** Optimiert: 10–20 %
** Überversorgung: > 20 %






=== Lagerlayout

* *Platzierung der Datendateien (.mdf)*
+
Trennen Sie Daten- und Protokolldateien auf unterschiedliche Laufwerke, um die Leistung zu verbessern, unabhängige Backup-Zeitpläne zu ermöglichen und die Wiederherstellungsfunktionalität zu verbessern. Für kleinere Datenbanken trennen Sie die LUN-Pfade für Daten und Protokolle in verschiedene Volumes. Diese Trennung ist erforderlich für mehr als eine große Datenbank (> 500 GiB).

* *Platzierung der Protokolldateien (.ldf)*
+
Trennen Sie Daten- und Protokolldateien auf unterschiedliche Laufwerke, um die Leistung zu verbessern, unabhängige Backup-Zeitpläne zu ermöglichen und die Wiederherstellungsfunktionalität zu verbessern. Für kleinere Datenbanken trennen Sie die LUN-Pfade für Daten und Protokolle in verschiedene Volumes. Diese Trennung ist erforderlich für mehr als eine große Datenbank (> 500 GiB).

* *TempDB-Platzierung*
+
Isolieren Sie die TempDB-E/A und vermeiden Sie E/A-Konflikte mit anderen Datenbanken, indem Sie TempDB auf einem eigenen Laufwerk platzieren. Diese Optimierung verbessert die Gesamtleistung und Stabilität des SQL-Servers. Wird dies nicht beachtet, kann es zu erheblichen E/A-Engpässen, einer langsameren Abfrageleistung und potenzieller Systeminstabilität kommen.





=== Storage-Konfiguration

* * ONTAP Konfiguration *
+
[cols="1a,1a,2a"]
|===
| Juristische Person | Einstellung | Empfehlung 


 a| 
Volumen
 a| 
** Thin Provisioning (-space-guarantee = none)
** Automatische Größenanpassung aktiviert
** Automatischer Größenmodus = wachsen
** Teilreserve = 0 %
** Snapshot-Kopienreserve = 0 %
** Automatisches Löschen von Snapshots (Volume/ältester zuerst)
** Space-mgmt-try-first = volume_grow

 a| 
Um die Speichereffizienz und Kosteneffektivität zu optimieren, konfigurieren Sie Thin Provisioning, Autosize und Speicherverwaltungsoptionen für Ihre FSx for ONTAP Volumes. Ohne Thin Provisioning wird Speicherplatz im Voraus zugewiesen, was zu ineffizienter Nutzung und höheren Kosten aufgrund von Überprovisionierung führt; statische Zuweisung führt dazu, dass für ungenutzte Kapazität bezahlt wird, was die Ausgaben erhöht; fehlende dynamische Zuweisung behindert Skalierbarkeit und Flexibilität und beeinträchtigt die Leistung; und ohne Speicherplatzrückgewinnung belegen gelöschte Daten Speicherplatz, was die Effizienz verringert.



 a| 
Volumen
 a| 
** Tiering-Richtlinie = nur Snapshot
** Tiering-minimum-cooling-days = 7

 a| 
Für eine optimale Datenbankleistung und Kosteneffizienz empfiehlt Workload Factory, nur Snapshots in die Kapazitätsebene zu verschieben. Diese Strategie gewährleistet hohe Leistung bei gleichzeitiger Kostenreduzierung. Es wird insbesondere empfohlen, Snapshots, die älter als 7 Tage sind, in verschiedene Kategorien einzuteilen.



 a| 
LUN
 a| 
Betriebssystemtyp = Windows 2008
 a| 
ONTAP LUN-OS-Typ-Wert sollte mit dem Partitionierungsschema des Betriebssystems übereinstimmen, um eine I/O-Ausrichtung zu erreichen. Eine falsche Konfiguration kann zu suboptimaler Leistung führen.



 a| 
LUN
 a| 
Platzreservierung aktiviert
 a| 
Wenn die Speicherplatzreservierung aktiviert ist, reserviert ONTAP genügend Speicherplatz im Volume, sodass Schreibvorgänge auf diese LUNs nicht aufgrund von Speicherplatzmangel fehlschlagen.



 a| 
LUN
 a| 
Speicherplatzzuweisung aktiviert
 a| 
Diese Option stellt sicher, dass FSx for ONTAP den EC2-Host benachrichtigt, wenn das Volume voll ist und keine Schreibvorgänge mehr annehmen kann. Diese Einstellung ermöglicht es FSx for ONTAP außerdem, Speicherplatz automatisch freizugeben, wenn SQL Server auf dem EC2-Host Daten löscht. Wenn diese Funktion deaktiviert ist, sind Schreibfehler möglich und der Speicherplatz wird möglicherweise ineffizient genutzt.

|===
* *Windows-Speicherkonfiguration*
+
[cols="1a,1a,2a"]
|===
| Juristische Person | Einstellung | Empfehlung 


 a| 
Microsoft Multipath I/O (MPIO)
 a| 
** Status = Aktiviert
** Richtlinie = Round Robin
** Anzahl der Sitzungen = 5

 a| 
Um eine optimale Verfügbarkeit und Datenzugriffskonsistenz für Microsoft SQL Server-Datenbanken auf EC2 mit zugrunde liegenden LUNs, die in FSx für ONTAP bereitgestellt werden, zu gewährleisten, empfiehlt Workload Factory die Aktivierung und Konfiguration von Multipath I/O (MPIO). MPIO bietet mehrere Pfade zu FSx für ONTAP und verbessert so sowohl die Ausfallsicherheit als auch die Leistung. Diese bewährte Vorgehensweise schützt vor potenziellen Datenverlusten oder Ausfallzeiten, indem der Datenzugriff auch dann aufrechterhalten wird, wenn eine Komponente ausfällt.



 a| 
Größe der Zuteilungseinheit
 a| 
NTFS-Zuordnungseinheitsgröße = 64 KB
 a| 
Legen Sie die NTFS-Zuordnungseinheitsgröße auf 64K fest, um den Speicherplatz besser zu nutzen, die Fragmentierung zu reduzieren und die Lese-/Schreibleistung von Dateien zu verbessern. Eine fehlerhafte Konfiguration kann zu ineffizienter Festplattennutzung und Leistungseinbußen führen.

|===




=== Berechnen

* *Die richtige Dimensionierung berechnen*
+
Um eine optimale Leistung und Kosteneffizienz Ihrer SQL Server EC2-Instanz zu gewährleisten, empfehlen wir, die Größe an Ihre Arbeitslastanforderungen anzupassen. Falls Ihre aktuelle Instanz unterdimensioniert ist, verbessert ein Upgrade die CPU-, Speicher- und E/A-Kapazität. Bei einer Überdimensionierung kann durch eine Herabstufung die Leistungsfähigkeit erhalten und gleichzeitig die Kosten gesenkt werden.

* *Betriebssystem-Patch*
+
Workload Factory empfiehlt, die neuesten Patches anzuwenden, um die Sicherheit zu gewährleisten, SQL Server Datenbanken vor Schwachstellen zu schützen und die Systemzuverlässigkeit zu verbessern.

* *Netzwerkadaptereinstellungen*
+
Eine genaue Konfiguration der Empfangsseitenskalierung (RSS) ist für eine optimale Netzwerkleistung in Microsoft SQL Server-Instanzen unerlässlich. RSS verteilt die Netzwerkverarbeitung auf mehrere Prozessoren, wodurch Engpässe vermieden und die Systemleistung verbessert werden. Workload Factory empfiehlt die folgenden RSS-Einstellungen:

+
** TCP-Offloading-Funktionen deaktivieren: Stellen Sie sicher, dass alle TCP-Offloading-Funktionen deaktiviert sind.
** Anzahl der Empfangswarteschlangen: Auf 8 setzen, wenn vCPUs > 8. Auf die Anzahl der vCPUs setzen, falls vCPUs ≤ 8.
** RSS-Profil: Auf NUMAStatic eingestellt.
** Basisprozessornummer: Auf 2 einstellen.
+
Durch die Einhaltung dieser Einstellungen verbessern Sie die Leistung und Zuverlässigkeit Ihrer Microsoft SQL Server-Instanzen. Wir empfehlen Ihnen, die empfohlenen Einstellungen zu testen, um Leistungsverbesserungen festzustellen, bevor Sie Änderungen an Ihrer Produktionsumgebung vornehmen.







=== Anwendung (SQL Server)

* *Lizenz*
+
Die Bewertung und Empfehlung der SQL Server-Lizenz erfolgt auf Hostebene.

+
Nicht optimiert: Eine Lizenz gilt als "nicht optimiert", wenn Workload Factory feststellt, dass Ihre Datenbankinfrastruktur keine der Funktionen der kommerziellen Softwarelizenz nutzt, für die Sie bezahlen. Eine nicht optimierte Lizenz kann zu unnötigen Kosten führen.

+
Optimiert: Eine Lizenz gilt als "optimiert", wenn die kommerzielle Softwarelizenz für Ihre Datenbanken Ihre Leistungsanforderungen erfüllt.

* *Microsoft SQL Server-Patch*
+
Workload Factory empfiehlt, die neuesten Patches anzuwenden, um die Sicherheit zu gewährleisten, SQL Server Datenbanken vor Schwachstellen zu schützen und die Systemzuverlässigkeit zu verbessern.

* *MAXDOP*
+
Um die Abfrageleistung durch einen Ausgleich der parallelen Verarbeitung zu optimieren, sollte der maximale Parallelisierungsgrad (MAXDOP) festgelegt werden. Eine präzise MAXDOP-Konfiguration verbessert Leistung und Effizienz. Die besten Ergebnisse werden in den meisten Anwendungsfällen erzielt, wenn MAXDOP auf 4, 8 oder 16 eingestellt wird. Wir empfehlen Ihnen, Ihre Arbeitslast zu testen und auf alle mit Parallelität zusammenhängenden Wartearten wie z. B. CXPACKET zu achten.





=== Zuverlässigkeit

* *FSx für ONTAP Backups planen*
+
Die Sicherung Ihrer Microsoft SQL Server-Volumes ist unerlässlich, um Ihre Anforderungen an Datenaufbewahrung und Compliance zu erfüllen. Verwenden Sie FSx for ONTAP Backup, um automatische Backups und Aufbewahrung für Ihre SQL Server-Daten einzurichten.

* *Lokale Snapshots planen*
+
Planen Sie lokale Snapshots für effiziente Datensicherung und schnelle Wiederherstellung. Snapshots sind Momentaufnahmen Ihrer Volumes zu einem bestimmten Zeitpunkt.

* *Regionenübergreifende Replikation*
+
Die regionsübergreifende Replikation stellt sicher, dass Ihre Daten in eine andere AWS-Region repliziert werden und bietet so eine verbesserte Datenbeständigkeit und Verfügbarkeit. Workload Factory empfiehlt die Einrichtung der regionsübergreifenden Replikation, um bei der Notfallwiederherstellung und Compliance zu unterstützen.





== Bewährte Verfahren und Empfehlungen für EVS-Workloads

Workload Factory bietet Best Practices und Empfehlungen für den Betrieb gut entwickelter Amazon Elastic VMware Service (EVS) Workloads. Die Well-Architected-Analyse bewertet EVS-Konfigurationen, um sicherzustellen, dass Ihre VMware-Umgebungen für Zuverlässigkeit, Sicherheit, betriebliche Exzellenz, Kostenoptimierung und Leistungseffizienz optimiert sind. Auf der Registerkarte „Well-Architected-Status“ in VMware finden Sie Einblicke und Empfehlungen, die Ihnen helfen, Well-Architected-Best-Practices für Ihre EVS-Umgebungen umzusetzen.

Die gut strukturierte Analyse kategorisiert Konfigurationen in den folgenden Säulen des Frameworks: _reliability_ und _security_.



=== Zuverlässigkeit

Zuverlässigkeit gewährleistet, dass Arbeitslasten ihre beabsichtigten Funktionen auch bei Störungen korrekt und konsistent erfüllen.

* *EVS-Umgebungsresilienz*
+
Stellen Sie sicher, dass Ihre EVS-Clusterknoten korrekt auf Partition Placement Groups verteilt sind. Alle Knoten sollten Mitglieder einer einzigen Partition Placement Group sein, die mit vier oder mehr Partitionen konfiguriert ist. Die richtige Partition Placement stellt sicher, dass Ihre EVS-Clusterknoten auf mehrere fehlerisolierte Hardwarepartitionen innerhalb einer AWS Availability Zone verteilt sind. Eine Fehlanordnung kann zu erheblichem Verlust an Rechenleistung oder Ausfallzeiten führen, wenn eine Partition ausfällt.





=== Sicherheit

Im Bereich der Sicherheit liegt der Schwerpunkt auf dem Schutz von Daten, Systemen und Vermögenswerten durch Risikobewertungen und Risikominderungsstrategien.

* *Cluster-Knoten-Verwaltung*
+
Stellen Sie sicher, dass Ihre EVS-Clusterknoten über einen geeigneten EC2-Stopp- und Beendigungsschutz verfügen. EVS ESXi-Knoten sollten ausschließlich mit vCenter oder anderen VMware-Verwaltungstools verwaltet werden. Ohne entsprechenden EC2-Schutz können Knoten versehentlich über die EC2-Konsole gestoppt oder beendet werden, was zur Nichtverfügbarkeit von virtuellen Maschinendaten oder zu Datenverlust führen kann.





== Ähnliche Informationen

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Implementieren Sie gut strukturierte FSx-Dateisysteme für ONTAP."^]
* link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementieren Sie gut strukturierte Datenbank-Workloads"^]
* link:https://docs.netapp.com/us-en/workload-vmware/view-evs-well-architected.html["Implementieren Sie gut strukturierte EVS-Konfigurationen"^]

