---
sidebar: sidebar 
permalink: whats-next.html 
keywords: what you can do 
summary: Nachdem Sie sich angemeldet und die Workload Factory eingerichtet haben, können Sie FSX für ONTAP-Dateisysteme erstellen und verwalten und andere Funktionen für die Workload Factory verwenden. 
---
= Was Sie bei der BlueXP -Workload-Fabrik als nächstes tun können
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Nachdem Sie sich jetzt angemeldet und die BlueXP -Workload-Fabrik eingerichtet haben, können Sie verschiedene Funktionen für die Workload-Fabrik nutzen, wie z. B. das Erstellen von Amazon FSX für ONTAP-Dateisystemen, das Bereitstellen von Datenbanken auf FSX für ONTAP-Dateisystemen und das Migrieren der Konfigurationen von Virtual Machines zu VMware Cloud auf AWS mithilfe von FSX für ONTAP-Dateisystemen als externe Datastores.

* https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["Amazon FSX für NetApp ONTAP"^]
+
Bewerten und analysieren Sie aktuelle Datenbestände auf mögliche Kosteneinsparungen durch Einsatz von FSX for ONTAP als Storage-Infrastruktur, Bereitstellung und Vorlagenatisierung von FSX für ONTAP Implementierungen basierend auf Best Practices und Zugriff auf erweiterte Managementfunktionen.

* https://docs.netapp.com/us-en/workload-genai/index.html["GenAI"^]
+
Durch die Implementierung und das Management einer RAG-Infrastruktur (Retrieval-Augmented Generation) werden die Genauigkeit und Einzigartigkeit Ihrer KI-Applikationen verbessert. Erstellen Sie eine RAG Knowledge Base auf FSX for ONTAP mit integrierter Datensicherheit und Compliance.

* https://docs.netapp.com/us-en/workload-databases/index.html["Datenbank-Workloads"^]
+
Erkennen Sie Ihren vorhandenen Datenbankbestand auf AWS, ermitteln Sie potenzielle Kosteneinsparungen durch einen Wechsel zu FSX für ONTAP, implementieren Sie Datenbanken durchgängig mit integrierten Best Practices zur Optimierung und automatisieren Sie Thin Cloning für CI/CD-Pipelines.

* https://docs.netapp.com/us-en/workload-vmware/index.html["VMware-Workloads"^]
+
Optimieren Sie Migrationen und Betriebsabläufe mithilfe intelligenter Empfehlungen und automatischer Problembehebung. Implementieren Sie effiziente Backups und zuverlässige Disaster Recovery. Überwachen Sie Ihre VMs und beheben Sie Fehler.


