= E-Mail-Benachrichtigungen für Workload Factory
:allow-uri-read: 




[[email-notifications-for-workload-factory]]
=== E-Mail-Benachrichtigungen für Workload Factory

Sie können Workload Factory-Benachrichtigungen jetzt per E-Mail erhalten, ohne ein Amazon SNS-Thema konfigurieren zu müssen. Aktivieren Sie E-Mail-Benachrichtigungen, um Benachrichtigungen an alle mit dem Konto verknüpften E-Mail-Adressen zu senden.

Sie können E-Mail-Benachrichtigungen entweder über die Workload Factory Console oder die NetApp Console konfigurieren. Die NetApp Console bietet außerdem die Möglichkeit, NetApp Console-Benachrichtigungen zu konfigurieren, die unter dem Glockensymbol angezeigt werden.

Wenn Sie Benachrichtigungen in der NetApp Console konfigurieren, übernimmt die NetApp Console die Zustellung der Benachrichtigungen. Die Benachrichtigungseinstellungen in der NetApp Workload Factory-Konsole werden schreibgeschützt, um doppelte Benachrichtigungen zu vermeiden.



[[new-notification-for-eda-latency]]
=== Neue Benachrichtigung für EDA-Latenz

Der NetApp Workload Factory-Benachrichtigungsdienst umfasst die Benachrichtigung für EDA-Latenz, die Sie benachrichtigt, wenn die Latenz einer EDA-Operation einen bestimmten Schwellenwert überschreitet.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Konfigurieren von Workload Factory-Benachrichtigungen"]



[[new-notification-for-fsx-for-ontap-file-systems]]
=== Neue Benachrichtigung für FSx für ONTAP-Dateisysteme

Der NetApp Workload Factory-Benachrichtigungsdienst beinhaltet eine Benachrichtigung mit einer monatlichen Kostenübersicht für Ihr Konto, die Ausgabentrends, ungewöhnliche Änderungen und die besten Einsparmöglichkeiten für FSx für ONTAP-Dateisysteme aufzeigt.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Konfigurieren von Workload Factory-Benachrichtigungen"]
